KTSHOP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('dashboard/',include('superadmin.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from cart import views
app_name = 'App_Cart'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('', views.cart_view, name="cart"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
    path('success/<int:id>', views.ordersuccess, name="success"),
]

shop/urls.py
from django.urls import path
from shop import views
app_name="App_Shop"
urlpatterns = [
    path('',views.Shop,name="shop"),
    path('details/<int:id>',views.ProductDetails,name="singleproduct"),
    path('category/<int:id>',views.CategoryProducts,name="category"),
    path('login',views.Loginview,name="login"),
    path('loginout',views.LogOutview,name="logout"),
]

cart/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from shop.models import *
from KTSHOP import settings


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="cart")
    item = models.ForeignKey(Products, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quantity} X {self.item}'

    def get_total(self):
        total = self.item.price * self.quantity
        float_total = format(total, '0.2f')
        return float_total


class Order(models.Model):
    orderitems = models.ManyToManyField(Cart)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    customer_name = models.CharField(max_length=264, blank=True, null=True)
    customer_phone = models.CharField(max_length=200, blank=True, null=True)
    customer_address = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return '{}'.format(str(self.user))

    def get_cart_count(self):
        return self.orderitems.count()

    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += float(order_item.get_total())
        return total


class SellingList(models.Model):
    seller=models.ForeignKey(User,on_delete=models.DO_NOTHING)
    customerName=models.CharField(max_length=100)
    customerPhone=models.CharField(max_length=13)
    customerAddress=models.CharField(max_length=100,blank=True)
    amount=models.FloatField(default=0)
    sellingDate=models.DateTimeField(auto_now=True,auto_now_add=False)

    def __str__(self):
        return '{}-{}'.format(self.seller,self.amount)

    def go_to_success(self):
        return reverse('App_Cart:success', kwargs={'id': self.id})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from cart.models import *
from django.contrib import messages
from shop.models import *


# Create your views here.
@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Products, pk=pk)
    order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item[0].quantity += 1
            order_item[0].save()
            messages.info(request, "This item quantity was updated.", extra_tags="cart")
            return redirect('App_Shop:shop')
        else:
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart.", extra_tags="cart")
            return redirect('App_Shop:shop')
    else:
        order = Order(user=request.user)
        order.save()
        order.orderitems.add(order_item[0])
        messages.info(request, "This item was added to your cart.", extra_tags="cart")
        return redirect('App_Shop:shop')


@login_required
def cart_view(request):
    carts = Cart.objects.filter(user=request.user, purchased=False)
    orders = Order.objects.filter(user=request.user, ordered=False)
    if request.method == "POST":
        customerName = request.POST.get('customer_name')
        customerPhone = request.POST.get('customer_phone')
        customerAddress = request.POST.get('customer_address')
        customerTotal = request.POST.get('total')
        print(customerName, customerAddress, customerPhone, customerTotal)
        selling = SellingList(seller=request.user)
        selling.customerName = customerName
        selling.customerPhone = customerPhone
        selling.customerAddress = customerAddress
        selling.amount = customerTotal
        selling.save()
        orders.delete()
        adjustCart(request.user)
        return redirect(selling.go_to_success())
    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request, 'cart/shop-cart.html', context={'carts': carts, 'order': order})
    else:
        messages.warning(request, "You don't have any item in your cart!")
        return redirect("App_Shop:shop")


def adjustCart(user):
    carts = Cart.objects.filter(user=user, purchased=False)
    for i in carts.all():
        product=Products.objects.get(id=i.item_id)
        product.stock=product.stock-i.quantity
        product.save()
        i.delete()


def ordersuccess(request, id):
    if id:
        return render(request, 'cart/success.html')
    else:
        return redirect('App_Shop:shop')


def remove_from_cart(request, pk):
    item = get_object_or_404(Products, pk=pk)
    if request.user.is_authenticated:
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.orderitems.filter(item=item).exists():
                order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
                order.orderitems.remove(order_item)
                order_item.delete()
                messages.warning(request, "This item was removed form your cart", extra_tags="cart")
                return redirect("App_Cart:cart")
            else:
                messages.info(request, "This item was not in your cart.", extra_tags="cart")
                return redirect("App_Shop:shop")
        else:
            messages.info(request, "You don't have an active order", extra_tags="cart")
            return redirect("App_Shop:shop")


def increase_cart(request, pk):
    item = get_object_or_404(Products, pk=pk)
    if request.user.is_authenticated:
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.orderitems.filter(item=item).exists():
                order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
                if order_item.quantity >= 1:
                    order_item.quantity += 1
                    order_item.save()
                    messages.info(request, f"{item.name} quantity has been updated", extra_tags="cart")
                    return redirect("App_Cart:cart")
            else:
                messages.info(request, f"{item.name} is not in your cart", extra_tags="cart")
                return redirect("App_Shop:shop")
        else:
            messages.info(request, "You don't have an active order", extra_tags="cart")
            return redirect("App_Shop:shop")


def decrease_cart(request, pk):
    item = get_object_or_404(Products, pk=pk)
    if request.user.is_authenticated:
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.orderitems.filter(item=item).exists():
                order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
                if order_item.quantity > 1:
                    order_item.quantity -= 1
                    order_item.save()
                    messages.info(request, f"{item.name} quantity has been updated", extra_tags="cart")
                    return redirect("App_Cart:cart")
                else:
                    order.orderitems.remove(order_item)
                    order_item.delete()
                    messages.warning(request, f"{item.name} item has been removed from your cart", extra_tags="cart")
                    return redirect("App_Cart:cart")
            else:
                messages.info(request, f"{item.name} is not in your cart", extra_tags="cart")
                return redirect("App_Shop:shop")
        else:
            messages.info(request, "You don't have an active order", extra_tags="cart")
            return redirect("App_Shop:shop")

templates/cart/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/cart/shop-cart.html
{% extends 'shop/base.html' %}
{% load dashboard %}
{% load static %}
{% block title %}
Cart Zone
{% endblock %}

{% block content %}
 <main class="page-wrapper">

      <div class="page-title-overlap bg-dark pt-4">
        <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
          <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">

          </div>
          <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
            <h1 class="h3 text-light mb-0">Your cart</h1>
          </div>
        </div>
      </div>
      <div class="container pb-5 mb-2 mb-md-4">
        <div class="row">
          <!-- List of items-->
          <section class="col-lg-8">
            <div class="d-flex justify-content-between align-items-center pt-3 pb-4 pb-sm-5 mt-1">
            <h4 class="text-white">Order Process</h4>
            </div>
          {%for message in messages %}
                     {%if "cart" in message.tags %}
                      <div class="alert alert-primary" role="alert">
                     {{ message }}
                    </div>
                {% endif %}
              {% endfor %}
            <!-- Item-->
             {% for cart in carts %}
            <div class="d-sm-flex justify-content-between align-items-center my-2 pb-3 border-bottom">
              <div class="d-block d-sm-flex align-items-center text-center text-sm-start">
                   <a class="btn btn-danger btn-sm" href="{% url 'App_Cart:remove' pk=cart.item.id %}"><span class="fs-sm">X</span></a>
                  <a class="d-inline-block flex-shrink-0 mx-auto me-sm-4" href="{% url 'App_Shop:singleproduct' cart.item.id %}">
                      <img src="{{ cart.item.photo.url }}" style="width: 80px;padding: 10px;" alt="Product"></a>
                <div class="pt-2" style="width: 22rem;">
                  <h3 class="product-title fs-base mb-2">
                      <a href="{% url 'App_Shop:singleproduct' cart.item.id %}">{{ cart.item.name }}</a></h3>
                  <div class="fs-sm">
                      <span class="text-muted"></span>{{ cart.item.category }}
                  </div>
                  <div class="fs-lg text-accent pt-2">{{ cart.item.price }}</div>
                </div>
              </div>
              <div class="pt-2 pt-sm-0 ps-sm-3 mx-auto mx-sm-0 text-center text-sm-start" style="max-width: 9rem;">
               <div class="m-0">
                    <label class="form-label" for="quantity1">Selling Price</label>
                <input  class="col form-control" id="price_{{ cart.id }}" onblur="adjustTotal()" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*?)\..*/g, '$1').replace(/^0[^.]/, '0');" type="text" min="{{ cart.item.price }}" value="{{ cart.item.price }}">
                <input  class="col form-control" id="quantity_{{ cart.id }}" type="hidden"  value="{{ cart.quantity }}">
               </div>
              </div>
              <div class="pt-2 pt-sm-0 ps-sm-3 mx-auto mx-sm-0 text-center text-sm-start" style="max-width: 11rem;">
                <label class="form-label" for="quantity1">Quantity</label>
                  <div style="display: inline-flex;flex-direction: row;gap: 12px;">
                      <div>
                          <a href="{% url 'App_Cart:decrease' pk=cart.item.id %}" class="btn btn-danger btn-sm">-</a>
                      </div>
                      <div>
                          <input  class="form-control" type="text" id="quantity1" min="1" disabled value="{{ cart.quantity }}">
                      </div>
                      <div>
                          <a href="{% url 'App_Cart:increase' pk=cart.item.id %}" class="btn btn-success btn-sm">+</a>
                      </div>
                  </div>

              </div>
            </div>
            {% endfor %}
          </section>
          <!-- Sidebar-->
          <aside class="col-lg-4 pt-4 pt-lg-0 ps-xl-5">
            <div class="bg-white rounded-3 shadow-lg p-4">
              <form method="post" class="py-2 px-xl-2">{% csrf_token %}
                <div class="text-center mb-4 pb-3 border-bottom">
                  <h2 class="h6 mb-3 pb-1">Total</h2>
                  <h3 class="fw-normal" id="totalPrice"> {{order.get_totals | floatformat:0 }} &#2547 </h3>
                </div>
                <div class="mb-3 mb-4">
                  <label class="form-label mb-3" for="order-comments">
                      <span class="fw-medium">Customer Name</span>
                  </label>
                  <input class="form-control"  required name="customer_name" id="order-comments"/>
                </div>
                <div class="mb-3 mb-4">
                  <label class="form-label mb-3" for="order-comments">
                      <span class="fw-medium">Phone No</span>
                  </label>
                  <input class="form-control" required name="customer_phone"  id="order-comments"/>
                </div>
                <div class="mb-3 mb-4">
                  <label class="form-label mb-3" for="order-comments">
                      <span class="fw-medium">Address</span>
                  </label>
                  <input class="form-control" name="customer_address" id="order-comments"/>
                </div>
                <div class="accordion" id="order-options">
                </div>
                  <input type="hidden" name="total" value="" id="exacttotal">
                  <button type="submit" class="btn btn-primary btn-shadow d-block w-100 mt-4">
                  <i class="fa fa-arrow-right fs-lg me-2"></i>Proceed Order</button>
              </form>
            </div>
          </aside>
        </div>
      </div>
    </main>


    <script>
    var cartitem=parseInt(document.getElementById("getcartTotals").innerHTML);
    console.log(cartitem);
    if (parseInt(cartitem) > 0){
        adjustTotal();
    }
    function adjustTotal(){
            let total=0;
          {% for cart in carts %}
            var actualPrice="{{ cart.item.price }}";
            var x=document.getElementById("price_{{ cart.id }}").value;
            var y=document.getElementById("quantity_{{ cart.id }}").value;
             if(parseInt(x)< parseInt(actualPrice)){
                 alert("You can not Sell Less then your actual price");
                 document.getElementById("price_{{ cart.id }}").value="{{ cart.item.price }}";
                 window.location.href = "{% url 'App_Cart:cart' %}";
                 document.getElementById("exacttotal").value="{{cart.item.price}}";
             }
             else{
                 total+=parseFloat(x)*parseInt(y);
                 document.getElementById("totalPrice").innerHTML=`${total} ৳`;
                 document.getElementById("exacttotal").value=total;
             }
         {% endfor %}
    console.log(total);
    }

    </script>
{% endblock %}

templates/cart/success.html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Success</h1>
        <p>Product Selling Done<br/> Please Collect Money from Customer Before Confirm Selling!</p>
        <a href="{% url 'App_Shop:shop' %}"><b>Back Home</b></a>
      </div>
    </body>
</html>