KTSHOP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('dashboard/',include('superadmin.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from cart import views
app_name = 'App_Cart'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('', views.cart_view, name="cart"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
    path('success/<int:id>', views.ordersuccess, name="success"),
]

shop/urls.py
from django.urls import path
from shop import views
app_name="App_Shop"
urlpatterns = [
    path('',views.Shop,name="shop"),
    path('details/<int:id>',views.ProductDetails,name="singleproduct"),
    path('category/<int:id>',views.CategoryProducts,name="category"),
    path('login',views.Loginview,name="login"),
    path('loginout',views.LogOutview,name="logout"),
]

superadmin/urls.py
from django.urls import path
from superadmin import views
app_name="App_Admin"
urlpatterns = [
    path('',views.Dashboard,name="dashboard"),
    path('sales-list',views.SalesList,name="saleslist"),
    path('bill-list',views.AddExpense,name='addexpense'),
    path('categories',views.CategoryView,name='category'),
]

shop/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


def upload_products_image(instance, filename):
    return "products/{name}/{filename}".format(name=instance, filename=filename)


class Category(models.Model):
    name = models.CharField(max_length=100)
    icon = models.FileField(upload_to="CategoryImages", default="default.svg")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Category"

    def get_product_count(self):
        products = Products.objects.filter(category=self)
        return products.count()


class Products(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    description = RichTextField(blank=True)
    price = models.FloatField(default=10.0)
    photo = models.ImageField(upload_to=upload_products_image, default='default.jpg')
    stock = models.IntegerField(default=0)
    create_at = models.DateField(auto_now=True, auto_now_add=False, null=True)

    def __str__(self):
        return '{}-{}'.format(self.name, self.category)

    class Meta:
        verbose_name_plural = "Products"


class ProductPurchase(models.Model):
    product = models.ForeignKey(Products, on_delete=models.DO_NOTHING)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    quantity = models.IntegerField(default=0)
    price = models.FloatField(default=0.0)
    timestamp = models.DateField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return '{}-{}'.format(self.product.name, self.quantity)


@receiver(post_save, sender=ProductPurchase)
def update_Product(sender, instance, created, **kwargs):
    if created:
        p = Products.objects.get(id=instance.product.id)
        product_price = p.price
        purchase_price = instance.price / instance.quantity
        if product_price > purchase_price:
            p.stock = p.stock + instance.quantity
            p.save()
        else:
            pp = ProductPurchase.objects.get(id=instance.id)
            pp.delete()
            print("You can not set product price less then your purchase price")



SELECT_BILL = (
    ('shop rent', 'Shop Rent'),
    ('electricity bill', 'Electricity Bill'),
    ('wifi bill', 'Wifi Bill'),
    ('donation', 'Donation'),
    ('tea bill', 'Tea Bill'),
    ('customer related', 'Customer Related'),
    ('friends related', 'Friends Related'),
    ('others', 'others'),

)


class MyBill(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    billName = models.CharField(max_length=50, choices=SELECT_BILL)
    total = models.FloatField(default=0.0)
    timestamp = models.DateField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return '{}-{}'.format(self.user, self.total)

shop/forms.py
from django import forms
from shop.models import MyBill,Category


SELECT_BILL = (
    ('shop rent', 'Shop Rent'),
    ('electricity bill', 'Electricity Bill'),
    ('wifi bill', 'Wifi Bill'),
    ('donation', 'Donation'),
    ('tea bill', 'Tea Bill'),
    ('customer related', 'Customer Related'),
    ('friends related', 'Friends Related'),
    ('others', 'others'),

)

class BillForm(forms.ModelForm):
    billName=forms.CharField(label="Select Bill Type",widget=forms.Select(choices=SELECT_BILL))
    class Meta:
        model = MyBill
        fields = ['billName', 'total']

shop/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from shop.models import *
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from cart.models import *

# Create your views here.

@login_required(login_url="App_Shop:login")
def Shop(request):
    categories = Category.objects.all().order_by("name")
    products = Products.objects.all().order_by("-id")
    carts = Cart.objects.filter(user=request.user, purchased=False)
    orders = Order.objects.filter(user=request.user, ordered=False)

    page = request.GET.get('page', 1)
    paginator = Paginator(products, 16)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    context = {
        'categories': categories,
        'products': products,
        'paginator': paginator,
        'carts': carts,
        'order': orders,
    }
    return render(request, 'shop/index.html', context)


@login_required(login_url="App_Shop:login")
def CategoryProducts(request, id):
    categories = Category.objects.all().order_by("name")
    products = Products.objects.filter(category_id=id).order_by("-id")
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 16)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    context = {
        'categories': categories,
        'products': products,
        'paginator': paginator,
        'category': Category.objects.get(id=id)
    }
    return render(request, 'shop/category.html', context)


def ProductDetails(request, id):
    categories = Category.objects.all().order_by("name")
    product=Products.objects.get(id=id)
    carts = Cart.objects.filter(user=request.user, purchased=False)
    orders = Order.objects.filter(user=request.user, ordered=False)

    suggests=Products.objects.filter(category=product.category).exclude(id=product.id)

    context = {
        'categories': categories,
        'product': product,
        'suggests':suggests,
        'carts': carts,
        'order': orders,
    }
    return render(request, 'shop/singleproduct.html',context)


def ShopCart(request):
    return render(request, 'shop/shop-cart.html')


def Loginview(request):
    try:
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            next = request.GET.get("next", '')
            user = authenticate(request, username=username, password=password)
            print(user)
            if user is not None:
                login(request, user)
                if next != "":
                    return redirect(next)
                return redirect('App_Shop:shop')
            else:
                messages.info(request, "Enter correct username and password", extra_tags="login_error")
            return redirect('App_Shop:login')
        return render(request, 'login/login.html')
    except:
        return redirect('App_Shop:login')


def LogOutview(request):
    logout(request)
    return redirect('App_Shop:login')

templates/shop/base.html
<!DOCTYPE html>
{% load static %}
{% load cart_tag %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}
    Khan Telecom
    {% endblock %}</title>
    <!-- SEO Meta Tags-->
    <meta name="description" content="Js tutul, tutul,Tutul, Jafor sadik tutul">
    <meta name="keywords" content="khan telecom,Khan Telecom, js tutul, jafor sadik tutul,tutul">
    <meta name="author" content="Jafor sadik tutul">
    <!-- Viewport-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
    <!-- Vendor Styles including: Font Icons, Plugins, etc.-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
    <link rel="stylesheet" media="screen" href="{% static 'vendor/simplebar/dist/simplebar.min.css' %}"/>
    <link rel="stylesheet" media="screen" href="{% static 'vendor/tiny-slider/dist/tiny-slider.css' %}"/>
    <!-- Main Theme Styles + Bootstrap-->
  <style>
      a.disabled {
  pointer-events: none;
  cursor: default;
}
  </style>
    <link rel="stylesheet" media="screen" href="{% static 'css/theme.min.css' %}">
  </head>
  <!-- Body-->
  <body class="bg-secondary">
    <!-- Navbar-->
    <header class="bg-light shadow-sm fixed-top" data-fixed-element>
      <div class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand d-none d-sm-block me-3 me-xl-4 flex-shrink-0" href="{% url 'App_Shop:shop' %}">
{#            <img src="img/logo-dark.png" width="142" alt="Cartzilla">#}
                Khan Telecom
            </a>
            <a class="navbar-brand d-sm-none me-2" href="{% url 'App_Shop:shop' %}">
{#                <img src="img/logo-icon.png" width="74" alt="Cartzilla">#}
                Khan Telecom
            </a>
          <!-- Search-->
          <div class="input-group d-none d-lg-flex flex-nowrap mx-4"><i class="fa fa-search position-absolute top-50 start-0 translate-middle-y ms-3"></i>
            <input class="form-control rounded-start w-100" type="text" placeholder="Search for products">
          </div>
          <!-- Toolbar-->
          <div class="navbar-toolbar d-flex flex-shrink-0 align-items-center ms-xl-2">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#sideNav">
                <span class="navbar-toggler-icon"></span>
            </button>
              <a class="navbar-tool d-flex d-lg-none" href="#searchBox" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="searchBox"><span class="navbar-tool-tooltip">Search</span>
              <div class="navbar-tool-icon-box">
                  <i class="navbar-tool-icon fa fa-search"></i>
              </div>
              </a>
                {% if request.user.is_authenticated %}
              <a class="navbar-tool ms-1 ms-lg-0 me-n1 me-lg-2" href="{% url 'App_Admin:dashboard' %}">
                <div class="navbar-tool-icon-box">
                    <i class="navbar-tool-icon fa fa-user"></i>
                </div>
                <div class="navbar-tool-text ms-n3">
                    <small>Hello, {{request.user}}</small>
                    Dashboard
                </div>
              </a>

            <div class="navbar-tool dropdown ms-3">
                <a class="navbar-tool-icon-box bg-secondary dropdown-toggle" href="{% url 'App_Cart:cart' %}">
                    <span class="navbar-tool-label" id="getcartTotals">{{ request.user|cart_total }}</span>
                    <i class="navbar-tool-icon fa fa-shopping-cart"></i>
                </a>
              <div class="dropdown-menu dropdown-menu-end">
                <div class="widget widget-cart px-3 pt-2 pb-3" style="width: 20rem;">
                  <div style="height: 15rem;" data-simplebar data-simplebar-auto-hide="false">
                     {% for cart in carts %}
                       <div class="widget-cart-item pb-2 border-bottom">
                      <button class="btn-close text-danger" type="button" aria-label="Remove">
                          <span aria-hidden="true">&times;</span>
                      </button>
                      <div class="d-flex align-items-center">
                          <a class="d-block" href="">
                              <img src="{{ cart.item.photo.url }}" width="64" alt="Product">
                          </a>
                        <div class="ps-2">
                          <h6 class="widget-product-title">
                              <a href="">{{ cart.item.name }}</a>
                          </h6>
                          <div class="widget-product-meta">
                              <span class="text-accent me-2">{{ cart.item.price }}</span>
                              <span class="text-muted">x {{ cart.quantity }}</span>
                          </div>
                        </div>
                      </div>
                    </div>
                      {% endfor %}
                  </div>
                  <div class="d-flex flex-wrap justify-content-between align-items-center pt-3">
                    <div class="fs-sm me-2 py-2">
                        <span class="text-muted">Total:</span>
                        <span class="text-accent fs-base ms-1">
                          &#2547 {{request.user|cart_total_amount }}
                        </span>
                    </div>
                      <a class="btn btn-primary btn-sm" href="{% url 'App_Cart:cart' %}">
                          Checkout
                          <i class="fa fa-arrow-right ms-1 me-n1"></i>
                      </a>
                  </div>
                </div>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
      <!-- Search collapse-->
      <div class="collapse" id="searchBox">
        <div class="card pt-2 pb-4 border-0 rounded-0">
          <div class="container">
            <div class="input-group"><i class="ci-search position-absolute top-50 start-0 translate-middle-y ms-3"></i>
              <input class="form-control rounded-start" type="text" placeholder="Search for products">
            </div>
          </div>
        </div>
      </div>
    </header>
    {% block content %}
    
    {% endblock %}
    <!-- Back To Top Button--><a class="btn-scroll-top" href="#top" data-scroll data-fixed-element><span class="btn-scroll-top-tooltip text-muted fs-sm me-2">Top</span><i class="btn-scroll-top-icon fa fa-arrow-up">   </i></a>
    <!-- Vendor scrits: js libraries and plugins-->
    <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/simplebar/dist/simplebar.min.js' %}"></script>
    <script src="{% static 'vendor/tiny-slider/dist/min/tiny-slider.js' %}"></script>
    <script src="{% static 'vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>
    <!-- Main theme script-->
    <script src="{% static 'js/theme.min.js' %}"></script>
  </body>
</html>

templates/shop/category.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
{{ category.name }}
{% endblock %}
{% block content %}
    {% include 'shop/leftbar.html' %}
    <main class="offcanvas-enabled" style="padding-top: 5rem;">
      <section class="ps-lg-4 pe-lg-3 pt-4">
        <div class="px-3 pt-2">
          <section class="d-md-flex justify-content-between align-items-center mb-4 pb-2">
            <h1 class="h2 mb-3 mb-md-0 me-3">{{paginator.count}} Products Found</h1>
          </section>
          <!-- Product grid-->
          <div class="row g-0 mx-n2">
              {% for product in products %}
              <div class="col-xl-3 col-lg-6 col-md-4 col-sm-6 px-2 mb-3">
                    <div class="card product-card card-static pb-3">
                        <span class="badge bg-danger badge-shadow">stock {{ product.stock }}</span>
                        <a class="card-img-top d-block overflow-hidden fix-img-size" href="{% url 'App_Shop:singleproduct' product.id %}">
                            <img src="{{ product.photo.url }}" alt="Product">
                        </a>
                        <div class="card-body py-2">
                         <a class="product-meta d-block fs-xs pb-1" href="{% url 'App_Shop:category' product.category.id %}">{{ product.category.name }}</a>
                         <h3 class="product-title fs-sm text-truncate">
                             <a data-toggle="tooltip" data-placement="top" title=" {{ product.name }}" href="{% url 'App_Shop:singleproduct' product.id %}">
                                {{ product.name }}
                             </a>
                         </h3>
                         <div class="product-price"><span class="text-accent">{{ product.price }}<small>৳</small></span>
                         </div>
                      </div>
                        <div class="product-floating-btn">
                         <button class="btn btn-primary btn-shadow btn-sm" type="button">+<i class="fa fa-shopping-cart fs-base ms-1"></i></button>
                      </div>
                    </div>
              </div>
              {% empty %}
                  <div class="alert alert-danger" role="alert">
                  There is No Product
                </div>
              {% endfor %}
          </div>
          <div class="py-4 pb-md-5 mb-4">
            <!-- Pagination-->
              {% if products.has_other_pages %}
                  <nav class="d-flex justify-content-between pt-2" aria-label="Page navigation">
                      {% if products.has_previous %}
                      <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}"><i class="fa fa-arrow-left me-2"></i>Prev</a></li>
                      </ul>
                      {% else %}
                      <ul class="pagination">
                        <li class="page-item"><a class="page-link" disabled=""><i class="fa fa-arrow-left me-2"></i>Prev</a></li>
                      </ul>
                      {% endif %}
                       <ul class="pagination">
                       {% for i in products.paginator.page_range %}
                           {% if products.number == i %}
                            <li class="page-item active d-none d-sm-block" aria-current="page"><span class="page-link">{{ i }}<span class="visually-hidden">(current)</span></span></li>
                           {% else %}
                            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                           {% endif %}
                       {% endfor %}
                       </ul>
                      {% if products.has_next %}
                      <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next">Next<i class="fa fa-arrow-right ms-2"></i></a></li>
                      </ul>
                      {% else %}
                      <ul class="pagination">
                        <li class="page-item"><a class="page-link"disabled="" aria-label="Next">Next<i class="fa fa-arrow-right ms-2"></i></a></li>
                      </ul>
                      {% endif %}
                </nav>
              {% endif %}
          </div>
        </div>
      </section>
      <!-- Footer-->
      <footer class="footer bg-dark pt-2">
        <div class="text-center text-white">
            © Design and Developed by --
            <a class="text-white" href="https://createx.studio/" target="_blank">Jafor Sadik Tutul | 01817552828  </a></div>
      </footer>
    </main>
{% endblock %}

templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
    {% include 'shop/leftbar.html' %}
    <main class="offcanvas-enabled" style="padding-top: 5rem;">
      <section class="ps-lg-4 pe-lg-3 pt-4">
        <div class="px-3 pt-2">
          <section class="d-md-flex justify-content-between align-items-center mb-4 pb-2">
            <h1 class="h2 mb-3 mb-md-0 me-3">{{paginator.count}} Products Found</h1>
          </section>
          <!-- Product grid-->
          <div class="row g-0 mx-n2">
              {% for product in products %}
              <div class="col-xl-3 col-lg-6 col-md-4 col-sm-6 px-2 mb-3">
                    <div class="card product-card card-static pb-3">
                        <span class="badge bg-danger badge-shadow">stock {{ product.stock }}</span>
                        <a class="card-img-top d-block overflow-hidden fix-img-size" href="{% url 'App_Shop:singleproduct' product.id %}">
                            <img src="{{ product.photo.url }}" alt="Product">
                        </a>
                        <div class="card-body py-2">
                         <a class="product-meta d-block fs-xs pb-1" href="{% url 'App_Shop:category' product.category.id %}">{{ product.category.name }}</a>
                         <h3 class="product-title fs-sm text-truncate">
                             <a data-toggle="tooltip" data-placement="top" title=" {{ product.name }}" href="{% url 'App_Shop:singleproduct' product.id %}">
                                {{ product.name }}
                             </a>
                         </h3>
                         <div class="product-price"><span class="text-accent">{{ product.price }} <small>৳</small></span>
                         </div>
                      </div>
                   <div class="product-floating-btn">
                      <a href="{% url 'App_Cart:add' product.id %}"
                         {% if product.stock > 0 %}
                         class="btn btn-primary btn-shadow btn-sm"
                         {% else %}
                           class="btn btn-primary btn-shadow btn-sm disabled"
                          {% endif %}

                         type="button">+<i class="fa fa-shopping-cart fs-base ms-1"></i></a>
                    </div>
                    </div>
              </div>
              {% empty %}
                  <div class="alert alert-danger" role="alert">
                  There is No Product
                </div>
              {% endfor %}
          </div>
          <div class="py-4 pb-md-5 mb-4">
            <!-- Pagination-->
              {% if products.has_other_pages %}
                  <nav class="d-flex justify-content-between pt-2" aria-label="Page navigation">
                      {% if products.has_previous %}
                      <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}"><i class="fa fa-arrow-left me-2"></i>Prev</a></li>
                      </ul>
                      {% else %}
                      <ul class="pagination">
                        <li class="page-item"><a class="page-link" disabled=""><i class="fa fa-arrow-left me-2"></i>Prev</a></li>
                      </ul>
                      {% endif %}
                       <ul class="pagination">
                       {% for i in products.paginator.page_range %}
                           {% if products.number == i %}
                            <li class="page-item active d-none d-sm-block" aria-current="page"><span class="page-link">{{ i }}<span class="visually-hidden">(current)</span></span></li>
                           {% else %}
                            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                           {% endif %}
                       {% endfor %}
                       </ul>
                      {% if products.has_next %}
                      <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next">Next<i class="fa fa-arrow-right ms-2"></i></a></li>
                      </ul>
                      {% else %}
                      <ul class="pagination">
                        <li class="page-item"><a class="page-link"disabled="" aria-label="Next">Next<i class="fa fa-arrow-right ms-2"></i></a></li>
                      </ul>
                      {% endif %}
                </nav>
              {% endif %}
          </div>
        </div>
      </section>
      <!-- Footer-->
      <footer class="footer bg-dark pt-2">
        <div class="text-center text-white">
            © Design and Developed by --
            <a class="text-white" href="https://createx.studio/" target="_blank">Jafor Sadik Tutul | 01817552828  </a></div>
      </footer>
    </main>
{% endblock %}

templates/shop/leftbar.html
<aside class="offcanvas offcanvas-expand w-100 border-end zindex-lg-5 pt-lg-5" id="sideNav" style="max-width: 21.875rem;">
      <div class="pt-2 d-none d-lg-block"></div>
      <ul class="nav nav-tabs nav-justified mt-4 mt-lg-5 mb-0" role="tablist" style="min-height: 3rem;">
        <li class="nav-item"><a class="nav-link fw-medium active" href="#categories" data-bs-toggle="tab" role="tab">Categories</a></li>
        <li class="nav-item d-lg-none"><a class="nav-link fs-sm" href="#" data-bs-dismiss="offcanvas" role="tab"><i class="fa fa-close fs-xs me-2"></i>Close</a></li>
      </ul>
      <div class="offcanvas-body px-0 pt-3 pb-0" data-simplebar>
        <div class="tab-content">
          <!-- Categories-->
          <div class="sidebar-nav tab-pane fade show active" id="categories" role="tabpanel">
            <div class="widget widget-categories">
              <div class="accordion" id="shop-categories">
                  {% for category in categories %}
                    <div class="accordion-item border-bottom">
                      <h3 class="accordion-header px-grid-gutter">
                          <a class="nav-link-style d-block fs-md fw-normal py-3" href="{% url 'App_Shop:category' category.id %}">
                              <span class="d-flex align-items-center">
                                  <img src = "{{ category.icon.url }}" class="text-danger mt-n1 me-2" alt="{{ category.name }} Image" style="width:30px;height: 30px"/>
                                  {{ category.name }} ({{ category.get_product_count }})
                              </span>
                          </a>
                      </h3>

                    </div>
                  {% endfor %}
              </div>
            </div>
          </div>


        </div>
      </div>
      <div class="offcanvas-footer d-block px-grid-gutter pt-4 pb-4 mb-2">
        <div class="d-flex mb-3"><i class="fa fa-user h4 mb-0 fw-normal text-primary mt-1 me-1"></i>
          <div class="ps-2">
            <div class="text-muted fs-sm">Support</div><a class="nav-link-style fs-md" href="tel:+8801817552828">01817552828</a>
          </div>
        </div>
        <div class="d-flex mb-3"><i class="fa fa-envelope h5 mb-0 fw-normal text-primary mt-1 me-1"></i>
          <div class="ps-2">
            <div class="text-muted fs-sm">Email</div><a class="nav-link-style fs-md" href="mailto:customer@example.com">jstutul30@gmail.com</a>
          </div>
        </div>
      </div>
    </aside>

templates/shop/singleproduct.html
{% extends 'shop/base.html' %}
{% block title %}
{{product.name}}
{% endblock %}

{% block content %}
    {% include 'shop/leftbar.html' %}

    <main class="offcanvas-enabled" style="padding-top: 5rem;">
      <section class="ps-lg-4 pe-lg-3 pt-4">
        <div class="px-3 pt-2">
          <!-- Page title + breadcrumb-->
          <!-- Content-->
          <!-- Product Gallery + description-->
          <section class="row g-0 mx-n2 pb-5 mb-xl-3">
            <div class="col-xl-7 px-2 mb-3">
              <div class="h-100 bg-light rounded-3 p-4">
                <div class="product-gallery">
                  <div class="product-gallery-preview order-sm-2">
                    <div class="product-gallery-preview-item active" id="first">
                        <img src="{{ product.photo.url }}" alt="Product image">
                    </div>
                    <div class="product-gallery-preview-item" id="second">
                        <img src="{{ product.photo.url }}" alt="Product image">
                    </div>
                    <div class="product-gallery-preview-item" id="third">
                       <img src="{{ product.photo.url }}" alt="Product image">
                    </div>
                  </div>
                  <div class="product-gallery-thumblist order-sm-1">
                      <a class="product-gallery-thumblist-item active" href="#first">
                        <img src="{{ product.photo.url }}" alt="Product image">
                      </a>
                      <a class="product-gallery-thumblist-item" href="#second">
                        <img src="{{ product.photo.url }}" alt="Product image">
                      </a>
                      <a class="product-gallery-thumblist-item" href="#third">
                         <img src="{{ product.photo.url }}" alt="Product image">
                      </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-5 px-2 mb-3">
              <div class="h-100 bg-light rounded-3 py-5 px-4 px-sm-5">
                  <a class="product-meta d-block fs-sm pb-2" href="{% url 'App_Shop:category' product.category.id %}">{{ product.category }}</a>
                <h1 class="h2">{{ product.name }}</h1>
                <div class="h2 fw-normal text-accent">{{product.price}}৳ </div>
                <div class="d-flex flex-wrap align-items-center pt-4 pb-2 mb-3">
                  <a href="{% url 'App_Cart:add' product.id %}"
                      {% if product.stock > 0 %}
                         class="btn btn-primary btn-shadow me-3 mb-3"
                      {% else %}
                        class="btn btn-primary btn-shadow me-3 mb-3 disabled"
                     {% endif %}

                     type="submit">
                      <i class="fa fa-shopping-cart fs-lg me-2"></i>
                      Add to Cart
                  </a>
                </div>
                <h6>Product description</h6>
                {{ product.description|safe }}
              </div>
            </div>
          </section>

        </div>
      </section>
      <!-- Footer-->

    </main>
{% endblock %}