KTSHOP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('dashboard/',include('superadmin.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from cart import views
app_name = 'App_Cart'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('', views.cart_view, name="cart"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
    path('success/<int:id>', views.ordersuccess, name="success"),
]

shop/urls.py
from django.urls import path
from shop import views
app_name="App_Shop"
urlpatterns = [
    path('',views.Shop,name="shop"),
    path('details/<int:id>',views.ProductDetails,name="singleproduct"),
    path('category/<int:id>',views.CategoryProducts,name="category"),
    path('login',views.Loginview,name="login"),
    path('loginout',views.LogOutview,name="logout"),
]

superadmin/urls.py
from django.urls import path
from superadmin import views
app_name="App_Admin"
urlpatterns = [
    path('',views.Dashboard,name="dashboard"),
    path('sales-list',views.SalesList,name="saleslist"),
    path('bill-list',views.AddExpense,name='addexpense'),
    path('categories',views.CategoryView,name='category'),
]

templates/dashboard/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Dashboard</title>
    <!-- SEO Meta Tags-->
    <meta name="description" content="Khan Telecom,js tutul,Tutul,jafor sadik tutul">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Vendor Styles including: Font Icons, Plugins, etc.-->
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
    <link rel="stylesheet" media="screen" href="{% static 'vendor/simplebar/dist/simplebar.min.css' %}"/>
    <link rel="stylesheet" media="screen" href="{% static 'vendor/tiny-slider/dist/tiny-slider.css' %}"/>
    <link rel="stylesheet" media="screen" href="{% static 'vendor/chartist/dist/chartist.min.css' %}"/>
    <link rel="stylesheet" media="screen" href="{% static 'vendor/prismjs/plugins/toolbar/prism-toolbar.css' %}"/>
    <link rel="stylesheet" media="screen" href="{% static 'vendor/prismjs/plugins/line-numbers/prism-line-numbers.css' %}"/>
    <link rel="stylesheet" media="screen" href="{% static 'vendor/flatpickr/dist/flatpickr.min.css' %}"/>
    <!-- Main Theme Styles + Bootstrap-->
    <link rel="stylesheet" media="screen" href="{% static 'css/theme.min.css' %}">
  </head>
  <!-- Body-->
  <body class="handheld-toolbar-enabled">

    <main class="page-wrapper">

      <header class="bg-light shadow-sm navbar-sticky">
        <div class="navbar navbar-expand-lg navbar-light">
          <div class="container">
              <a class="navbar-brand d-none d-sm-block flex-shrink-0 me-4 order-lg-1" href="{% url 'App_Shop:shop' %}">
                  Khan Telecom
              </a>
              <a class="navbar-brand d-sm-none me-2 order-lg-1" href="{% url 'App_Shop:shop' %}">
                  Khan Telecom
              </a>
            <!-- Toolbar-->
            <div class="navbar-toolbar d-flex align-items-center order-lg-3">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                  <span class="navbar-toggler-icon"></span>
              </button>
               <div class="navbar-toolbar d-flex flex-shrink-0 align-items-center ms-xl-2">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#sideNav">
                <span class="navbar-toggler-icon"></span>
            </button>
                {% if request.user.is_authenticated %}
              <a class="navbar-tool ms-1 ms-lg-0 me-n1 me-lg-2" href="{% url 'App_Admin:dashboard' %}">
                <div class="navbar-tool-icon-box">
                    <i class="navbar-tool-icon fa fa-user"></i>
                </div>
                <div class="navbar-tool-text ms-n3">
                    <small>Hello, {{request.user}}</small>
                    Dashboard
                </div>
              </a>
            {% endif %}
          </div>
            </div>
          </div>
        </div>
      </header>

      <!-- Dashboard header-->
      <div class="page-title-overlap bg-accent pt-4">
        <div class="container d-flex flex-wrap flex-sm-nowrap justify-content-center justify-content-sm-between align-items-center pt-2">
          <div class="d-flex">
            <div class="text-sm-start me-5">
              <h4 class="text-light">Welcome to Sales Dashboard</h4>
              <div class="text-light" id="txt"></div>
            </div>

          </div>
        </div>
      </div>

      <div class="container mb-5 pb-3">
        <div class="bg-light shadow-lg rounded-3 overflow-hidden">
          <div class="row">
            <!-- Sidebar-->
            <aside class="col-lg-3 pe-xl-5">
              <div class="h-100 border-end mb-2">
                <div class="d-lg-block collapse" id="account-menu">
                  <div class="bg-secondary p-4">
                    <h3 class="fs-sm mb-0 text-muted">Seller Dashboard</h3>
                  </div>
                  <ul class="list-unstyled mb-0">
                    <li class="border-bottom mb-0">
                        <a class="nav-link-style d-flex align-items-center px-4 py-3 active" href="{% url 'App_Admin:dashboard' %}">
                            <i class="fa fa-dashboard opacity-60 me-2"></i>
                            Dashboard
                        </a>
                    </li>
                    <li class="border-bottom mb-0">
                        <a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'App_Admin:saleslist' %}">
                            <i class="fa fa-dollar opacity-60 me-2"></i>
                            Sales
                        </a>
                    </li>
                    <li class="border-bottom mb-0">
                        <a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'App_Admin:addexpense' %}">
                            <i class="fa fa-cloud-upload opacity-60 me-2"></i>
                            Expense List
                        </a>
                    </li>
                    <li class="border-bottom mb-0">
                        <a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'App_Admin:category' %}">
                            <i class="fa fa-box-open opacity-60 me-2"></i>Category
                        </a>
                    </li>
                    <li class="mb-0">
                        <a class="nav-link-style d-flex align-items-center px-4 py-3" href="{% url 'App_Shop:logout' %}">
                            <i class="fa fa-sign-out opacity-60 me-2"></i>Sign out
                        </a>
                    </li>
                  </ul>
                  <hr>
                </div>
              </div>
            </aside>
            <!-- Content-->

            {% block dashboard %}

            {% endblock %}





          </div>
        </div>
      </div>
    </main>

    <footer class="footer bg-dark">

      <div class="pt-2">
            <div class="text-center text-white">© All rights reserved. Made by <a class="text-light" href="https://createx.studio/" target="_blank" rel="noopener">Createx Studio</a></div>
          </div>
    </footer>
    <!-- Toolbar for handheld devices (Marketplace)-->
    <div class="handheld-toolbar">
      <div class="d-table table-layout-fixed w-100">
          <a class="d-table-cell handheld-toolbar-item" href="dashboard-favorites.html">
              <span class="handheld-toolbar-icon">
                  <i class="ci-heart"></i>
              </span>
              <span class="handheld-toolbar-label">Favorites</span>
          </a>
          <a class="d-table-cell handheld-toolbar-item" href="javascript:void(0)" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" onclick="window.scrollTo(0, 0)"><span class="handheld-toolbar-icon"><i class="ci-menu"></i></span><span class="handheld-toolbar-label">Menu</span></a><a class="d-table-cell handheld-toolbar-item" href="marketplace-cart.html"><span class="handheld-toolbar-icon"><i class="ci-cart"></i><span class="badge bg-primary rounded-pill ms-1">3</span></span><span class="handheld-toolbar-label">$56.00</span></a></div>
    </div>
    <!-- Back To Top Button--><a class="btn-scroll-top" href="#top" data-scroll><span class="btn-scroll-top-tooltip text-muted fs-sm me-2">Top</span><i class="btn-scroll-top-icon fa fa-arrow-up">   </i></a>
    <!-- Vendor scrits: js libraries and plugins-->
    <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/simplebar/dist/simplebar.min.js' %}"></script>
    <script src="{% static 'vendor/tiny-slider/dist/min/tiny-slider.js' %}"></script>
    <script src="{% static 'vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>
    <script src="{% static 'vendor/chartist/dist/chartist.min.js' %}"></script>
    <script src="{% static 'vendor/prismjs/components/prism-core.min.js' %}"></script>
    <script src="{% static 'vendor/prismjs/components/prism-markup.min.js' %}"></script>
    <script src="{% static 'vendor/prismjs/components/prism-clike.min.js' %}"></script>
    <script src="{% static 'vendor/prismjs/components/prism-javascript.min.js' %}"></script>
    <script src="{% static 'vendor/prismjs/components/prism-pug.min.js' %}"></script>
    <script src="{% static 'vendor/prismjs/plugins/toolbar/prism-toolbar.min.js' %}"></script>
    <script src="{% static 'vendor/prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js' %}"></script>
    <script src="{% static 'vendor/prismjs/plugins/line-numbers/prism-line-numbers.min.js' %}"></script>
    <script src="{% static 'vendor/flatpickr/dist/flatpickr.min.js' %}"></script>
    <script src="{% static 'vendor/flatpickr/dist/plugins/rangePlugin.js' %}"></script>
    <!-- Main theme script-->
    <script src="{% static 'js/theme.min.js' %}"></script>
  <script>
      startTime();
    function startTime() {
      const today = new Date();
      let h = today.getHours();
      let m = today.getMinutes();
      let s = today.getSeconds();
      m = checkTime(m);
      s = checkTime(s);
      document.getElementById('txt').innerHTML =  h + ":" + m + ":" + s;
      setTimeout(startTime, 1000);
    }

    function checkTime(i) {
      if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
      return i;
    }
    </script>
    <script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
  <script src="{% static 'html2pdf.bundle.min.js' %}"></script>
    <script>
      {% block js %}

      {% endblock %}
  </script>
  </body>
</html>

templates/dashboard/category.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block dashboard %}


    <section class="col-lg-9 py-4" style="padding: 0px 4%;">
    <h3>Category List</h3>

    <div class="table-responsive">
        <table id="example" class="table table-striped" width="100%">
    <thead>
        <tr>
            <th>Sl</th>
            <th>Category Name</th>
            <th>Category Wise Product</th>
            <th>Icon</th>
        </tr>
    </thead>
    <tbody>
    {% for category in category %}
     <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ category.name }}</td>
            <td>{{ category.get_product_count }}</td>
            <td><img src="{{ category.icon.url  }}" width="40" height="40" alt="icon"></td>
     </tr>
    {% endfor %}


    </tbody>
</table>
    </div>
    </section>

 <script>
    var filterbutton=document.getElementById("filterBtn2");
    filterbutton.addEventListener('click',function () {
            document.getElementById("filterbill").submit();
    });

    </script>
{% endblock %}
 {% block js %}
window.setTimeout(function() {
$(".alert").fadeTo(500, 0).slideUp(500, function(){
$(this).remove();
});
}, 4000);
      {% endblock %}

templates/dashboard/dashboard-sales.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load dashboard %}
{% block dashboard %}
 <section class="col-lg-8 pt-lg-4 pb-4 mb-3">
              <div class="pt-2 px-4 ps-lg-0 pe-xl-5">
                <h2 class="h3 py-2 text-center text-sm-start">Statistic of Shop</h2>
                <div class="row mx-n2 pt-2">
                  <div class="col-md-4 col-sm-6 px-2 mb-4">
                    <div class="bg-secondary h-100 rounded-3 p-4 text-center">
                      <h3 class="fs-sm text-muted">Total Product</h3>
                      <p class="h2 mb-2">{{ request.user|total_product }}</p>
                    </div>
                  </div>

                  <div class="col-md-4 col-sm-6 px-2 mb-4">
                    <div class="bg-secondary h-100 rounded-3 p-4 text-center">
                      <h3 class="fs-sm text-muted">Total Sale Amount</h3>
                      <p class="h2 mb-2">৳ {{ request.user|total_sale }}</p>
                    </div>
                  </div>
                  <div class="col-md-4 col-sm-12 px-2 mb-4">
                    <div class="bg-secondary h-100 rounded-3 p-4 text-center">
                      <h3 class="fs-sm text-muted">Total product Sale</h3>
                      <p class="h2 mb-2">{{ request.user|total_product_sale }}</p>
                    </div>
                  </div>
                  <div class="col-md-4 col-sm-12 px-2 mb-4">
                    <div class="bg-secondary h-100 rounded-3 p-4 text-center">
                      <h3 class="fs-sm text-muted">Total Bill</h3>
                      <p class="h2 mb-2">৳ {{ request.user|total_bill }}</p>
                    </div>
                  </div>
                  <div class="col-md-4 col-sm-12 px-2 mb-4">
                    <div class="bg-secondary h-100 rounded-3 p-4 text-center">
                      <h3 class="fs-sm text-muted">Total Purchase</h3>
                      <p class="h2 mb-2">৳ {{ request.user|total_purchase_amount }}</p>
                    </div>
                  </div>
                    <div class="col-md-4 col-sm-12 px-2 mb-4">
                    <div class="bg-secondary h-100 rounded-3 p-4 text-center">
                      <h3 class="fs-sm text-muted">Total Income</h3>
                      <p class="h2 mb-2">৳ {{ request.user|total_income }}</p>
                    </div>
                  </div>
                </div>
{#                  line chart#}
                <div class="col-md-12">
                <form class="needs-validation" id="filterForm" method="post">{% csrf_token %}
                  <div class="row">
                    <div class="col-md-3 mb-3">
                      <select class="form-select" name="yearname" id="filterYear" required>
                        {% if year != "" %}
                        <option value="year" selected >{{ year }}</option>
                        {% endif %}
                        <option value="2022">2022</option>
                        <option value="2023">2023</option>
                        <option value="2024">2024</option>
                        <option value="2025">2025</option>
                        <option value="2026">2026</option>
                        <option value="2027">2027</option>
                        <option value="2028">2028</option>
                        <option value="2029">2029</option>
                      </select>
                    </div>
                  </div>
                </form>
               <div class="d-flex flex-wrap justify-content-center fs-ms">
              <div class="border rounded py-1 px-2 me-2 mb-2">
                <div class="d-inline-block align-middle me-1" style="width: .75rem; height: .75rem; background-color: #f34770;"></div>
                <span class="d-inline-block align-middle">Selling </span>
              </div>
              <div class="border rounded py-1 px-2 me-2 mb-2">
                <div class="d-inline-block align-middle me-1" style="width: .75rem; height: .75rem; background-color: #fea569;"></div>
                <span class="d-inline-block align-middle">Purchasing</span>
              </div>
            </div>
                <div class="ct-chart ct-perfect-fourth" data-bar-chart='{"labels": ["Jan", "Feb", "Mar", "Apr", "May", "Jun","Jul","Aug","Sept","Oct","Nov","Dec"], "series": [{{ getPursG }}, {{ getSellG }} ]}', data-series-color='{"colors": ["#f34770", "#fea569"]}'></div>
                </div>
              </div>
            </section>
    <section>

    </section>
    <script>
    document.getElementById("filterYear").addEventListener('change',function () {
        document.getElementById("filterForm").submit();
    })
    </script>
{% endblock %}

templates/dashboard/expenselist.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block dashboard %}


    <section class="col-lg-9 py-4" style="padding: 0px 4%;">

     <form class="needs-validation modal fade" method="post" id="add-address" tabindex="-1" novalidate> {% csrf_token %}
        <div class="modal-dialog modal-md">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Add a new Bill</h5>
              <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <div class="row gx-4 gy-3">
                {{ form|crispy }}
              </div>
            </div>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Close</button>
              <button class="btn btn-primary btn-shadow" type="submit">Add Bill</button>
            </div>
          </div>
        </div>
      </form>

    <h3>My Expense and Bill List</h3>
    <div class="pt-4">
        <a class="btn btn-primary" href="#add-address" data-bs-toggle="modal">Add Bill</a>
    </div>
        <div class="my-2" id="messagebar">
             {%for message in messages %}
            {%if "bill_add" in message.tags %}
            <div class="alert alert-success alert-dismissible" role="alert">
               {{ message }}
            </div>
            {% endif %}
            {% endfor %}
         </div>
    <form method="POST" class="row my-2" id="filterbill">{% csrf_token %}
                        <div class="col-md-6">
                            <div class="input-group" >
                          <span class="input-group-text">
                            <i class="fa fa-calendar"></i>
                          </span>
                          <input class="form-control date-picker date-range" value="{{ sDate }}" name="daterange" type="text" placeholder="From date" data-datepicker-options='{"altInput": true, "altFormat": "F j, Y","dateFormat": "Y-m-d"}' data-linked-input="#end-date">
                          <input class="form-control date-picker"  value="{{ eDate }}" type="text" placeholder="To date" data-datepicker-options='{"altInput": true, "altFormat": "F j, Y", "dateFormat": "Y-m-d"}' id="end-date">
                        </div>
                        </div>
                        <div class="col-md-4">
                           <div class="input-group" >
                             <span class="input-group-text">
                            <i class="fa fa-user"></i>
                          </span>
                              <select class="form-select" name="sellerName" id="validationCustom03">
                                <option value="">Choose</option>
                                  {% for user in sellers %}
                                      {% if sellerName == user.id %}
                                        <option value="{{ user.id }}" selected >{{ user }}</option>
                                      {% else %}
                                        <option value="{{ user.id }}">{{ user }}</option>
                                      {% endif %}
                                  {% endfor %}
                              </select>
                        </div>
                        </div>
                       <div class="col-md-2">
                            <div class="input-group" >
                              <select class="form-select" id="validationCustom03" name="pageNo">
                                <option value="10" >10</option>
                                <option value="20" >20</option>
                                <option value="50" >50</option>
                              </select>
                        </div>
                       </div>
                      <div class="col-md-1">
                            <div class="input-group" >
                                <input type="hidden" name="filterForm">
                              <button type="button" class="btn btn-outline-danger btn-sm my-2" id="filterBtn2">Filter</button>
                        </div>
                       </div>
                  </form>
    <div class="table-responsive">
        <table id="exampleexpense" class="table table-striped" width="100%">
    <thead>
        <tr>
            <th>Sl</th>
            <th>Seller</th>
            <th>Bill Type</th>
            <th>Amount</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
    {% for bill in mybill %}
     <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ bill.user }}</td>
            <td>{{ bill.billName }}</td>
            <td>{{ bill.total }}</td>
            <td>{{ bill.timestamp }}</td>
     </tr>
    {% endfor %}


    </tbody>
</table>
    </div>
    </section>

 <script>
    var filterbutton=document.getElementById("filterBtn2");
    filterbutton.addEventListener('click',function () {
            document.getElementById("filterbill").submit();
    });

    </script>
{% endblock %}
 {% block js %}
window.setTimeout(function() {
$(".alert").fadeTo(500, 0).slideUp(500, function(){
$(this).remove();
});
}, 4000);

    });

 {% endblock %}

templates/dashboard/sales.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block dashboard %}
<section class="col-lg-9 pt-lg-4 pb-4 mb-3">
              <div class="pt-2 px-4 ps-lg-0 pe-xl-5">
                <!-- Title-->
                <div class="d-sm-flex flex-wrap justify-content-between align-items-center border-bottom">
                  <h2 class="h3 py-2 me-2 text-center text-sm-start">Your Sales List
                      <span class="badge bg-faded-accent fs-sm text-body align-middle ms-2">{{ all_sales.count }}</span>
                  </h2>
                  <form method="POST" class="row my-2" id="filterSales">{% csrf_token %}
                        <div class="col-md-6">
                            <div class="input-group" >
                          <span class="input-group-text">
                            <i class="fa fa-calendar"></i>
                          </span>
                          <input name="startDate" value="{{ sDate }}" class="form-control date-picker" type="text" placeholder="From date" data-datepicker-options='{"altInput": true, "altFormat": "F j, Y", "dateFormat": "Y-m-d"}' data-linked-input="#end-date">
                          <input name="endDate" value="{{ eDate }}" class="form-control date-picker" type="text" placeholder="To date" data-datepicker-options='{"altInput": true, "altFormat": "F j, Y", "dateFormat": "Y-m-d"}' id="end-date">
                        </div>
                        </div>
                        <div class="col-md-4">
                           <div class="input-group" >
                             <span class="input-group-text">
                            <i class="fa fa-user"></i>
                          </span>
                              <select class="form-select" name="sellerName" id="validationCustom03">
                                <option value="">Choose</option>
                                  {% for user in sellers %}
                                      {% if sellerName == user.id %}
                                        <option value="{{ user.id }}" selected >{{ user }}</option>
                                      {% else %}
                                        <option value="{{ user.id }}">{{ user }}</option>
                                      {% endif %}
                                  {% endfor %}
                              </select>
                        </div>
                        </div>
                       <div class="col-md-2">
                            <div class="input-group" >
                              <select class="form-select" id="validationCustom03" name="pageNo">
                                <option value="5" >5</option>
                                <option value="10" >10</option>
                                <option value="20" >20</option>
                                <option value="50" >50</option>
                                <option value="100" >100</option>
                              </select>
                        </div>
                       </div>
                      <div class="col-md-1">
                            <div class="input-group" >
                              <button type="button" class="btn btn-outline-danger btn-sm my-2" id="filterBtn">Filter</button>

                        </div>
                       </div>
                  </form>
                </div>
                <!-- Product-->
                <button class="btn btn-warning btn-sm my-2" id="downloadpdf">Download Report</button>
                <div class="table-responsive" id="salesreport">

                  <table class="table table-hover">
                  {% if all_sales.count > 0 %}
                    <thead>
                      <tr>
                        <th>SL</th>
                        <th>Seller</th>
                        <th>C Name</th>
                        <th>C Address</th>
                        <th>C Phone</th>
                        <th>Total</th>
                        <th>Date</th>
                      </tr>
                    </thead>
                  {% endif %}
                    <tbody>
                      {% for sale in all_sales %}
                        <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ sale.seller }}</td>
                        <td>{{ sale.customerName }}</td>
                        <td>{{ sale.customerAddress }}</td>
                        <td>{{ sale.customerPhone }}</td>
                        <td>{{ sale.amount }}</td>
                        <td>{{ sale.sellingDate.date }}</td>
                      </tr>
                       {% empty %}
                          <div class="alert alert-dark alert-dismissible fade show" role="alert">
                          <span class="fw-medium">Data Not Found</span>
                        </div>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>

              </div>
            </section>


    <script>
    var filterbutton=document.getElementById("filterBtn");
    filterbutton.addEventListener('click',function () {
            document.getElementById("filterSales").submit();
    });


    </script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.debug.js"></script>
    <script>
    document.getElementById("downloadpdf").addEventListener('click',createPDF);
      function createPDF() {
        var sTable = document.getElementById('salesreport').innerHTML;
        var style = "<style>";
        style = style + "table {width: 100%;font: 17px Calibri;}";
        style = style + "table, th, td {border: solid 1px #DDD; border-collapse: collapse;";
        style = style + "padding: 2px 3px;text-align: center;}";
        style = style + "</style>";

        // CREATE A WINDOW OBJECT.
        var win = window.open('', '', 'height=700,width=700');

        win.document.write('<html><head>');
        win.document.write('<title>Profile</title>');   // <title> FOR PDF HEADER.
        win.document.write(style);          // ADD STYLE INSIDE THE HEAD TAG.
        win.document.write('</head>');
        win.document.write('<body>');
        win.document.write(sTable);         // THE TABLE CONTENTS INSIDE THE BODY TAG.
        win.document.write('</body></html>');

        win.document.close(); 	// CLOSE THE CURRENT WINDOW.

        win.print();    // PRINT THE CONTENTS.
    }
    </script>
{% endblock %}